### ISSUE TITLE
File names on Linux

### ISSUE THREAD

**Issue by lawrie** [wel97459/FPGACosmacELF#2]
I am running your simulation on Linux, but the file names such as verification\\test_FPM_Verification.bin don't work. If you change those to use use / instead, would they then work on all operating systems?

Also it would be helpful if you could put the log file verification\test_FPM_Verification.log in the repository.

I mainly use open source FPGA boards, and am interesting in getting this running on one of those boards, possibly a  Ulx3s board.

**Comment by wel97459** [comment]
I'll have to check it out on a Linux box.
I see what happened to test_FPM_Verification.log, the .gitignore kept it out of the repo.

**Comment by wel97459** [comment]
Can't do much about the file paths for Linux you will have to change them locally.
Added the test_FPM_Verification.log
And a basic OP Code verification.

**Comment by lawrie** [comment]
Thanks for that. The simulations are working for me now.
